using Xunit;
using LangChain.Databases.Mongo.Model;

namespace LangChain.Databases.MongoTests
{
    public class BaseEntityTests
    {
        [Fact]
        public void Id_ShouldBeAutoGenerated()
        {
            // Arrange
            var entity = new BaseEntity();

            // Assert
            Assert.NotEqual(Guid.Empty, entity.Id);
        }

        [Fact]
        public void IsActive_ShouldDefaultToTrue()
        {
            // Arrange
            var entity = new BaseEntity();

            // Assert
            Assert.True(entity.IsActive);
        }

        [Fact]
        public void CreatedDate_ShouldDefaultToUtcNow()
        {
            // Arrange
            var entity = new BaseEntity();

            // Assert
            Assert.Equal(DateTime.UtcNow.Date, entity.CreatedDate.Date);
        }

        [Fact]
        public void UpdatedDate_ShouldDefaultToUtcNow()
        {
            // Arrange 
            var entity = new BaseEntity();

            // Assert
            Assert.Equal(DateTime.UtcNow.Date, entity.UpdatedDate.Date);
        }
    }
}